/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gykj_paddle_lite_demo_tts_CalcMac */

#ifndef _Included_com_gykj_voicetts_CalcMac
#define _Included_com_gykj_voicetts_CalcMac


extern "C"
JNIEXPORT jstring JNICALL
Java_com_gykj_voicetts_CalcMac_Native_1JniCalcText(JNIEnv *env, jclass clazz,
                                                               jstring text) ;
extern "C"
JNIEXPORT void JNICALL
Java_com_gykj_voicetts_CalcMac_Native_1Jni(JNIEnv *env, jclass clazz,jstring text) ;
#endif



